plugins {
    id 'java'
    id 'war'
}

group = 'com.my'
version = '1.0-SNAPSHOT'
sourceCompatibility = '21'

repositories {
    mavenCentral()
}

dependencies {
    // Spring Framework
    implementation 'org.springframework:spring-context:6.1.3'
    implementation 'org.springframework:spring-webmvc:6.1.3'

    // Jakarta Servlet API
    providedCompile 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    providedCompile 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.1.1'

    // JSTL
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.0'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'

    // Test
    testImplementation 'junit:junit:4.13.2'
}

test {
    useJUnit()
}